from sqlalchemy import Column, String, Text, ForeignKey, Integer, Boolean, DateTime, JSON, func, Float
from sqlalchemy.orm import relationship
from backend.database import Base

class Customer(Base):
    __tablename__ = "customers"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id"), nullable=False)
    first_name = Column(String(100))
    last_name = Column(String(100))
    email = Column(String(255), index=True)
    phone = Column(String(50), index=True)
    company_name = Column(String(255))
    status = Column(String(50), default="active", nullable=False)
    plan = Column(String(50), default="Starter")
    usage_limit = Column(Integer, default=1000)
    usage_used = Column(Integer, default=0)
    avatar_url = Column(String(255))
    lifecycle_stage = Column(String(50))
    crm_status = Column(String(50))
    customer_type = Column(String(50), default="guest", nullable=False)
    session_id = Column(String(255), index=True)
    cust_id = Column(String(50), unique=True, index=True)
    auth_user_id = Column(String(50), index=True)
    converted_at = Column(DateTime(timezone=True))
    converted_by = Column(String(50))
    last_interaction_at = Column(DateTime(timezone=True))
    interaction_count = Column(Integer, default=0)
    stripe_customer_id = Column(String(255), index=True)
    stripe_subscription_id = Column(String(255), index=True)
    stripe_payment_method_id = Column(String(255))
    subscription_status = Column(String(50))
    current_period_end = Column(DateTime(timezone=True))
    last_contact_date = Column(DateTime(timezone=True))
    next_follow_up_date = Column(DateTime(timezone=True))
    lead_source = Column(String(100))
    tags = Column(JSON)
    converted_to_id = Column(String(50))
    original_guest_id = Column(String(50))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class Deal(Base):
    __tablename__ = "deals"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    customer_id = Column(String(50), ForeignKey("customers.id", ondelete="SET NULL"))
    title = Column(Text, nullable=False)
    description = Column(Text)
    value = Column(Integer)
    stage = Column(Text, nullable=False, default="lead")
    probability = Column(Integer, default=50)
    expected_close_date = Column(DateTime(timezone=True))
    source = Column(Text)
    assigned_to = Column(Text)
    notes = Column(Text)
    last_contact_date = Column(DateTime(timezone=True))
    next_follow_up_date = Column(DateTime(timezone=True), index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class Communication(Base):
    __tablename__ = "communications"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id"), nullable=False)
    type = Column(String(50), nullable=False)
    direction = Column(String(50), nullable=False)
    status = Column(String(50), nullable=False)
    duration = Column(Integer, default=0)
    transcript = Column(Text)
    summary = Column(Text)
    sentiment = Column(String(50))
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    ended_at = Column(DateTime(timezone=True))
    channel = Column(String(50))
    integration_id = Column(String(50), ForeignKey("integrations.id"))
    recording_url = Column(Text)
    user_identifier = Column(String(255))
    agent_id = Column(String(50), ForeignKey("agents.id", ondelete="SET NULL"))
    call_intent = Column(Text)
    call_outcome = Column(Text)
    call_context = Column(JSON)
    customer_id = Column(String(50), ForeignKey("customers.id"))
    twilio_call_sid = Column(Text)
    telnyx_call_id = Column(Text)
    retry_count = Column(Integer, default=0)
    parent_communication_id = Column(String(50))
    campaign_id = Column(Text)
    campaign_name = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class ConversationMessage(Base):
    __tablename__ = "conversation_messages"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id"), nullable=False)
    user_identifier = Column(String(255), nullable=False, index=True)
    channel = Column(String(50), nullable=False)
    role = Column(String(50), nullable=False)
    content = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    communication_id = Column(String(50), ForeignKey("communications.id"))
