from sqlalchemy import Column, String, Text, ForeignKey, Integer, Boolean, DateTime, JSON, func, Float
from sqlalchemy.orm import relationship
from backend.database import Base

class WorkerTemplate(Base):
    __tablename__ = "worker_templates"
    id = Column(String(50), primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    slug = Column(String(100), unique=True, nullable=False)
    description = Column(Text)
    category = Column(String(50), default="general")
    default_instructions = Column(Text)
    parameter_schema = Column(JSON, default={})
    required_tools = Column(JSON, default=[])
    required_integrations = Column(JSON, default=[])
    outcome_price = Column(Integer, default=0)
    evaluation_logic = Column(JSON, default={})
    icon = Column(String(50), default="bot")
    color = Column(String(20), default="orange")
    is_active = Column(Boolean, default=True)
    is_system = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class WorkerTask(Base):
    __tablename__ = "worker_tasks"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    template_id = Column(String(50), ForeignKey("worker_templates.id"))
    worker_type = Column(String(100), nullable=False)
    customer_id = Column(String(100))
    created_by_user_id = Column(String(50))
    status = Column(String(20), default="pending", nullable=False)
    input_data = Column(JSON, default={})
    output_data = Column(JSON)
    outcome_status = Column(String(50), default="pending_eval")
    outcome_score = Column(Float)
    steps_completed = Column(Integer, default=0)
    steps_total = Column(Integer)
    current_step = Column(String(255))
    logs = Column(JSON, default=[])
    error_message = Column(Text)
    tokens_used = Column(Integer, default=0)
    api_calls = Column(JSON, default={})
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    started_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    rating = Column(Integer)
    rating_feedback = Column(Text)
    rated_at = Column(DateTime(timezone=True))
    rated_by_user_id = Column(String(50))
    base_fee_cents = Column(Integer, default=0)
    token_fee_cents = Column(Integer, default=0)
    outcome_fee_cents = Column(Integer, default=0)
    total_fee_cents = Column(Integer, default=0)
    fee_billed = Column(Boolean, default=False)
    dispatched_by_agent_id = Column(String(50), ForeignKey("agents.id", ondelete="SET NULL"))

class WorkerSchedule(Base):
    __tablename__ = "worker_schedules"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    worker_type = Column(String(100), nullable=False)
    schedule_expression = Column(String(100), nullable=False)
    cron_expression = Column(String(100))
    timezone = Column(String(50), default="UTC")
    input_data = Column(JSON, default={})
    is_active = Column(Boolean, default=True)
    next_run_at = Column(DateTime(timezone=True), index=True)
    last_run_at = Column(DateTime(timezone=True))
    created_by_user_id = Column(String(50))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class WorkerInstance(Base):
    __tablename__ = "worker_instances"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(100), nullable=False)
    worker_type = Column(String(100), nullable=False)
    tier = Column(String(50), default="standard")
    files_disk_size_gb = Column(Integer, default=10)
    status = Column(String(50), default="provisioning")
    is_external = Column(Boolean, default=False)
    connection_url = Column(String(255))
    api_key_ref = Column(String(255))
    container_id = Column(String(255))
    ip_address = Column(String(50))
    monthly_cost_cents = Column(Integer, default=0)
    billing_start_date = Column(DateTime(timezone=True))
    created_by_user_id = Column(String(50))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class Campaign(Base):
    __tablename__ = "campaigns"
    id = Column(String(50), primary_key=True, index=True)
    workspace_id = Column(String(50), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(100), nullable=False)
    description = Column(Text)
    trigger_type = Column(String(50), nullable=False)
    trigger_event = Column(String(50))
    is_active = Column(Boolean, default=True)
    status = Column(String(50), default="active")
    stop_on_response = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    steps = relationship("CampaignStep", back_populates="campaign", order_by="CampaignStep.step_order", cascade="all, delete-orphan")

class CampaignStep(Base):
    __tablename__ = "campaign_steps"
    id = Column(String(50), primary_key=True, index=True)
    campaign_id = Column(String(50), ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=False)
    step_order = Column(Integer, nullable=False)
    type = Column(String(50), nullable=False)
    config = Column(JSON)
    delay_minutes = Column(Integer, default=0)
    time_reference = Column(String(50), default="previous_step")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    campaign = relationship("Campaign", back_populates="steps")

class CampaignEnrollment(Base):
    __tablename__ = "campaign_enrollments"
    id = Column(String(50), primary_key=True, index=True)
    campaign_id = Column(String(50), ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=False)
    customer_id = Column(String(50), ForeignKey("customers.id", ondelete="CASCADE"), nullable=False)
    reference_id = Column(String(50))
    current_step_order = Column(Integer, default=1)
    status = Column(String(50), default="active")
    next_run_at = Column(DateTime(timezone=True), index=True)
    last_run_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    error_message = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
