-- Migration: Create admin settings tables
-- Description: Tables for platform settings, API keys, sessions, and integration toggles

-- Admin Settings Table
CREATE TABLE IF NOT EXISTS admin_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_name VARCHAR(255) DEFAULT 'SupaAgent Inc.',
    support_email VARCHAR(255) DEFAULT 'support@supaagent.com',
    default_language VARCHAR(10) DEFAULT 'en-US',
    timezone VARCHAR(50) DEFAULT 'America/New_York',
    two_factor_enabled BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- API Keys Table
CREATE TABLE IF NOT EXISTS api_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    key_prefix VARCHAR(20) NOT NULL, -- e.g., 'sk_live_'
    key_hash VARCHAR(255) NOT NULL, -- hashed full key
    last_used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Active Sessions Table (FK to users will be added when users table exists)
CREATE TABLE IF NOT EXISTS active_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(20), -- Will add FK constraint later when users table exists
    device_name VARCHAR(255),
    location VARCHAR(255),
    ip_address VARCHAR(50),
    user_agent TEXT,
    last_active_at TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Platform Integrations Table (for admin toggles)
CREATE TABLE IF NOT EXISTS platform_integrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider VARCHAR(50) UNIQUE NOT NULL, -- 'slack', 'stripe', 'hubspot', 'sendgrid'
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_enabled BOOLEAN DEFAULT true,
    icon_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Insert default admin settings
INSERT INTO admin_settings (company_name, support_email, default_language, timezone)
VALUES ('SupaAgent Inc.', 'support@supaagent.com', 'en-US', 'America/New_York')
ON CONFLICT DO NOTHING;

-- Insert default platform integrations (COMMENTED OUT - Add real integrations as needed)
-- INSERT INTO platform_integrations (provider, display_name, description, is_enabled) VALUES
-- ('slack', 'Slack', 'Receive notifications and chatbot alerts directly in your Slack channels.', true),
-- ('stripe', 'Stripe', 'Sync customer billing data and handle subscription automatically.', true),
-- ('hubspot', 'HubSpot', 'Push leads generated by the chatbot directly into your CRM pipeline.', true),
-- ('sendgrid', 'SendGrid', 'Send transactional emails and follow-up sequences to your users.', false)
-- ON CONFLICT (provider) DO NOTHING;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_api_keys_key_prefix ON api_keys(key_prefix);
CREATE INDEX IF NOT EXISTS idx_active_sessions_user_id ON active_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_platform_integrations_provider ON platform_integrations(provider);
