
export const PRICING_PLANS = [
    {
        name: 'Pro',
        price: 12900,
        interval: 'month',
        description: 'Individual / Small Business',
        features: [
            '2 AI Personalities',
            '1 Local Phone Number',
            'Voice: $0.22 / min',
            'Chat: $0.06 / msg',
            'Basic Integrations (Cal, CRM)',
            'Standard HD Voice',
            'SSL / Encrypted',
        ],
        priceId: 'price_1SpuwS6Rc2ce57mvuoenTeSt',
        popular: false,
    },
    {
        name: 'Pro+',
        price: 34900,
        interval: 'month',
        description: 'Growing Business',
        features: [
            '8 AI Personalities',
            '3 Local Phone Numbers',
            'Voice: $0.15 / min',
            'Chat: $0.04 / msg',
            'Outcome Fee: $2.50 / booking',
            'Advanced Integrations (Webhooks)',
            'Premium Emotional Voice',
            'SOC2 / GDPR Compliance',
        ],
        priceId: 'price_1Spv0g6Rc2ce57mvskyImgME',
        popular: true,
    },
    {
        name: 'ProMax',
        price: 89900,
        interval: 'month',
        description: 'High Volume',
        features: [
            '25 AI Personalities',
            '10 Local Phone Numbers',
            'Voice: $0.09 / min',
            'Chat: $0.02 / msg',
            'Outcome Fee: $1.50 / booking',
            'Custom API Connectors',
            'Custom Voice Cloning',
            'SOC2 Type II Compliance',
        ],
        priceId: 'price_1Spv0j6Rc2ce57mv14JuYQcR',
        popular: false,
    },
    {
        name: 'Enterprise',
        price: null,
        interval: 'month',
        description: 'Healthcare / Gov',
        features: [
            'Unlimited AI Agents',
            'Volume Discounts',
            'Dedicated Engineering Support',
            'Low-Latency Edge Routing',
            'HIPAA + BAA Signed',
            'On-Prem / Private Cloud',
            'Negotiated ROI Model',
        ],
        popular: false,
        isEnterprise: true,
    },
];
